Build/pnpm
nl-design-system/nlds-community-blocks pull request #21
Opened 2024-01-25 10:18 UTC by matijs

- Add .npmrc with `save-exact=true` and `save-prefix=`
- Convert to pnpm from npm
  - Remove package-lock.json
  - Add pnpm-lock.yaml
- Update workflows/continuous-integration.yml
  - Replace the use of npm with pnpm
  - Update actions to their latest versions where possible
  - Precede the `actions/setup-node` step by the `pnpm/setup-action` step so the `actions/setup-node` can automatically set up the cache for this step
- Remove and re-add all dependencies that were not saved with their exact version
- wp-prettier is a drop-in replacement for prettier and should be called as prettier instead of wp-prettier
- Fix all linting issues

2024-01-25 11:42 UTC, matijs commented on .npmrc
> +shamefully-hoist=true
Zie https://pnpm.io/npmrc#shamefully-hoist

2024-01-25 11:46 UTC, matijs commented on package.json
> +	"name": "@nl-design-system-unstable/nlds-community-blocks",
Wat is hier wenselijk? Moet `.npmpackagejsonlintrc.json` aangepast worden, of juist `package.json`?

2024-01-25 12:02 UTC, Robbert requested changes

2024-01-25 12:02 UTC, Robbert commented on package.json
> +	"name": "@nl-design-system-unstable/nlds-community-blocks",
De linter moet aangepast worden, deze package is inderdaad the odd one out. Men wilde liever niet `unstable` in de naam. Liever toewerken naar stabiele betrouwbare releases met semver en zo min mogelijk breaking changes.

2024-01-25 12:02 UTC, Robbert commented on .npmrc
> +shamefully-hoist=true
Denk dat een comment hier op z'n plaats is, om even duidelijk te maken waarom deze erin moet staan. Dan kun je weten wat je moet testen om te kijken of deze setting er inmiddels uit kan.

2024-01-27 09:32 UTC, Robbert approved these changes

2024-01-27 09:33 UTC, merged