ci: check `composer install` in GitHub Actions
nl-design-system/nlds-community-blocks pull request #5
Opened 2023-11-26 10:31 UTC by Robbert

2023-11-27 13:47 UTC, richardkorthuis approved these changes

2023-11-27 15:24 UTC, paulAcato requested changes

2023-11-27 15:24 UTC, paulAcato commented on .github/workflows/php.yml
> +        php_version: "7.4"
Wij doen eigenlijk alles met PHP 8+

2023-12-04 09:55 UTC, Robbert commented on .github/workflows/php.yml
> +        php_version: "7.4"
Ik had uit `readme.txt` 7.4 gehaald:

https://github.com/nl-design-system/wordpress-gutenberg-blocks/blob/main/readme.txt#L6

Allebei aanpassen dan? Welke minor release zal ik instellen? De laatste van 8.x?

2023-12-04 10:34 UTC, richardkorthuis commented on .github/workflows/php.yml
> +        php_version: "7.4"
Wij ontwikkelen inderdaad (compatible) voor PHP 8+, maar in de readme staat 7.4 omdat het daar een minimum versie betreft. Stel deze plugin komt uiteindelijk in de WordPress Plugin Directory, dan zal de versie die daar staat bepalend zijn of de plugin wordt getoond aan de hand van de bij de gebruiker geïnstalleerde PHP versie. Dus stel op de server van de website staat 7.4 geïnstalleerd en wij hebben in de readme 8.0 staan, dan wordt de plugin dus niet getoond, omdat hij niet geschikt zou zijn.

2023-12-04 19:06 UTC, Robbert commented on .github/workflows/php.yml
> +        php_version: "7.4"
Ik test nu op 7.4 en op 8.3:

```
strategy:
   matrix:
     php_version: ["7.4", "8.3"]
```

en verderop:

```
with:
 php_version: ${{ matrix.php_version }}
```

2023-12-04 19:06 UTC, merged